"""Render docs/MODEL_CARD.md from reports/metrics.json.

Generated rather than hand-written so the card cannot drift from the numbers
the model actually produced -- the failure mode documented as audit #20.

Usage:
    python scripts/make_model_card.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
METRICS = ROOT / "reports" / "metrics.json"
OUTPUT = ROOT / "docs" / "MODEL_CARD.md"


def pct(x: float) -> str:
    return f"{x * 100:.2f}%"


def render(report: dict) -> str:
    cal = report["metrics"]["calibrated"]
    uncal = report["metrics"]["uncalibrated"]
    cv = report["metrics"]["cross_validation"]
    leaky = report["metrics"].get("leaky_split_demo")

    lines: list[str] = []
    add = lines.append

    add("# Model card: CrediWise credit risk classifier")
    add("")
    add("*Generated by `scripts/make_model_card.py` from `reports/metrics.json`.*")
    add(f"*Trained {report['trained_at']}.*")
    add("")
    add("## Intended use")
    add("")
    add("Classifies a customer-month into a credit standing band "
        "(Poor / Standard / Good) and returns calibrated probabilities, a "
        "policy decision and reason codes.")
    add("")
    add("**Intended:** demonstrating an auditable credit-risk pipeline — "
        "grouped validation, calibration, explainability and a bounded "
        "fairness audit.")
    add("")
    add("**Not intended:** real lending decisions. It is trained on a public "
        "synthetic dataset whose labels have no documented provenance, and "
        "six of the seven ECOA protected bases are absent from that data, so "
        "it cannot be cleared for discriminatory impact. See "
        "`docs/FAIRNESS.md`.")
    add("")
    add("## Data")
    add("")
    add(f"- {report['n_rows']:,} rows = **{report['n_customers']:,} customers "
        f"x 8 months**")
    add(f"- Bureau feature `Credit_Mix` "
        f"{'included' if report['include_bureau'] else 'excluded'}")
    add("- Split grouped on `Customer_ID`; no customer appears in both train "
        "and test")
    add("")
    add("## Performance")
    add("")
    add("All figures on a customer-disjoint holdout set of "
        f"{cal['n']:,} rows.")
    add("")
    add("| Metric | Value |")
    add("|---|---|")
    add(f"| Accuracy | **{pct(cal['accuracy'])}** |")
    add(f"| Majority-class baseline | {pct(cal['baseline_accuracy'])} |")
    add(f"| Lift over baseline | **+{cal['lift_over_baseline'] * 100:.2f} pts** |")
    add(f"| Macro-F1 | **{pct(cal['macro_f1'])}** |")
    add(f"| Weighted F1 | {pct(cal['weighted_f1'])} |")
    add(f"| Macro AUC (OvR) | {cal['macro_auc_ovr']:.3f} |")
    add(f"| Expected calibration error | {cal['expected_calibration_error']:.4f} |")
    add(f"| CV macro-F1 ({cv['folds']}-fold grouped) | "
        f"{pct(cv['mean'])} +/- {cv['std'] * 100:.2f} |")
    add("")
    add("### Per class")
    add("")
    add("| Class | AUC | Gini | KS | Brier |")
    add("|---|---|---|---|---|")
    for name, m in cal["per_class"].items():
        add(f"| {name} | {m['auc']:.3f} | {m['gini']:.3f} | {m['ks']:.3f} | "
            f"{m['brier']:.4f} |")
    add("")
    add("```")
    add(cal["report"].rstrip())
    add("```")
    add("")
    add("### Calibration")
    add("")
    add("| | Uncalibrated | Isotonic |")
    add("|---|---|---|")
    add(f"| Expected calibration error | "
        f"{uncal['expected_calibration_error']:.4f} | "
        f"**{cal['expected_calibration_error']:.4f}** |")
    add(f"| Macro-F1 | {pct(uncal['macro_f1'])} | {pct(cal['macro_f1'])} |")
    add("")
    add("Isotonic regression is fit on a customer-disjoint slice of the "
        "training data, never on rows the forest was fit on.")
    add("")

    if leaky:
        add("### Why this differs from the original notebook")
        add("")
        add("The same pipeline evaluated on a random row-level split, as the "
            "original notebook did:")
        add("")
        add("| Split | Accuracy | Macro-F1 | Customers in both sides |")
        add("|---|---|---|---|")
        add(f"| Random rows (leaky) | {pct(leaky['accuracy'])} | "
            f"{pct(leaky['macro_f1'])} | {leaky['shared_customers']:,} |")
        add(f"| Grouped by customer | {pct(cal['accuracy'])} | "
            f"{pct(cal['macro_f1'])} | 0 |")
        add("")
        add(f"A gap of **{(leaky['accuracy'] - cal['accuracy']) * 100:.2f} "
            f"points** of pure leakage. See `docs/AUDIT.md` #11.")
        add("")

    add("## Most important features")
    add("")
    add("Mean |SHAP| over a 1,000-row sample of the holdout set.")
    add("")
    add("| Feature | Mean \\|SHAP\\| |")
    add("|---|---|")
    for row in report["global_importance"][:10]:
        add(f"| {row['feature']} | {row['mean_abs_shap']:.4f} |")
    add("")
    add("## Fairness")
    add("")
    scope = report["fairness"]["_scope"]
    add(f"**Scope limit.** {scope['caveat']} Testable here: "
        f"{', '.join(scope['testable_ecoa_bases'])}. Untestable: "
        f"{', '.join(scope['untestable_ecoa_bases'])}.")
    add("")
    for dimension, result in report["fairness"].items():
        if dimension.startswith("_"):
            continue
        summary = result["summary"]
        if "disparate_impact_ratio" not in summary:
            continue
        verdict = "PASS" if summary["passes_four_fifths_rule"] else "**FAIL**"
        add(f"### `{dimension}`")
        add("")
        add(f"- Disparate impact ratio: **{summary['disparate_impact_ratio']:.3f}** "
            f"({verdict} against the four-fifths rule)")
        add(f"- Same ratio on the *labels* (base rates): "
            f"**{summary['base_rate_ratio']:.3f}**")
        amp = summary["amplification"]
        direction = "widens" if amp < 1 else "narrows"
        add(f"- Amplification: **{amp:.2f}** — the model {direction} the "
            f"disparity already present in the labels")
        add(f"- Selection rate range: "
            f"{summary['selection_rate_range'][0]:.3f} to "
            f"{summary['selection_rate_range'][1]:.3f} "
            f"(lowest: {summary['worst_group']}, highest: {summary['best_group']})")
        add(f"- Equal opportunity gap: {summary['equal_opportunity_gap']:.3f}")
        add(f"- Equalised odds gap: {summary['equalised_odds_gap']:.3f}")
        add(f"- Calibration gap: {summary['calibration_gap']:.3f}")
        if summary.get("excluded_from_ratio"):
            add(f"- Excluded from the ratio: "
                f"{', '.join(summary['excluded_from_ratio'])} "
                f"(missing-data buckets, not protected classes)")
        add("")
        add("| Group | n | Base rate | Selection rate | TPR | FPR | Accuracy | ECE |")
        add("|---|---|---|---|---|---|---|---|")
        for g in result["by_group"]:
            add(f"| {g['group']} | {g['n']:,} | {g['base_rate']:.3f} | "
                f"{g['selection_rate']:.3f} | {g['tpr']:.3f} | {g['fpr']:.3f} | "
                f"{g['accuracy']:.3f} | {g['ece']:.4f} |")
        add("")

    add("## Decision policy")
    add("")
    policy = report["policy"]
    add(f"- Approve when P(Good) >= {policy['approve_threshold']}")
    add(f"- Refer when P(Good) >= {policy['refer_threshold']}")
    add("- Decline otherwise, with reason codes")
    add("")
    add("Cost matrix (rows = truth, columns = predicted):")
    add("")
    add("| | Poor | Standard | Good |")
    add("|---|---|---|---|")
    for i, name in enumerate(["Poor", "Standard", "Good"]):
        row = policy["cost_matrix"][i]
        add(f"| **{name}** | {row[0]} | {row[1]} | {row[2]} |")
    add("")
    add("Illustrative weights: approving a genuinely Poor applicant is set to "
        "cost roughly three times as much as declining a genuinely Good one. "
        "A real deployment sets these from the lender's own loss data.")
    add("")
    add("## Limitations")
    add("")
    add("- Labels have no documented provenance; the source does not say how "
        "credit standing was assigned.")
    add("- Six of seven ECOA protected bases are absent, so no claim is made "
        "about race or sex fairness.")
    add("- The labels are age-correlated (16% of the 18-45 bands are Good "
        "against 33% of the 46-55 band), so disparity by age band reflects "
        "the dataset as much as the model.")
    add("- `Credit_Mix` is a bureau credit-quality judgement, making the task "
        "partly circular. `--no-bureau` quantifies the dependency.")
    add("- Trained on one 8-month window with no temporal holdout, so nothing "
        "here measures performance under drift.")
    return "\n".join(lines) + "\n"


def main() -> None:
    if not METRICS.exists():
        sys.exit(f"{METRICS} not found -- run `make train` first.")
    OUTPUT.write_text(render(json.loads(METRICS.read_text())))
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
